### ISSUE TITLE
Problem with SpeechServiceConnection_EndSilenceTimeoutMs Property

### ISSUE THREAD

**Issue by robshostak** [Azure-Samples/cognitive-services-speech-sdk#323]
This property (SpeechServiceConnection_EndSilienceTimeoutMs) seems to be controlling the maximum duration of an utterance rather than the max duration of silence at the end of the utterance before the recognizer considers the utterance ended.

I am testing this using the latest Java version  of the QuickStart  that recognizes from a microphone.   If I set the property to "1000", for example, then a long utterance will be cut off  after about a second even if the silence between words is much shorter than a second.   The property is set using the following Java code:

reco.getProperties().setProperty(PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, "1000");

Platform:   Windows 10
Language:  Java SE 10 
Hardware:  x64
Version of Java cognitive-services SDK: 1.6.0
Microphone:  Phillips Speech Mike Premium

**Comment by chrisbasoglu** [comment]
You are correct.  That was not intended.  This will need to be fixed in a future release.  We will open a backlog item.

**Comment by robshostak** [comment]
Thanks, Chris – how often are new versions released, typically?

**Comment by wolfma61** [comment]
the next refresh is scheduled for early September.

One additional note (independent of the SilenceTimeout-property), the quickstart sample is using RecognizeOnce. You will only receive one responds / result from this function. To receive more than one result, you will need to use ContinuousRecognition. 

Wolfgang

**Comment by robshostak** [comment]
Thanks, Wolfgang –

 

A couple of follow-up questions regarding the version of the SpeechRecognizer constructor that takes an AudioConfig:

 

If that config provides an AudioInputSteam:

 

(1)        Will the recognition stop automatically if the end of that stream is reached , both for the RecognizeOne and Continuous Recognition methods?

 

(2)       If we want to recognize once, but then, say a minute later, want to do a second recognition, will it be necessary to create a new SpeechRecognizer for the second recognition or can the first one be reused?

 

Kind regards-

Rob

**Comment by wolfma61** [comment]
For unrelated question I would recommend opening new issues, this way they get the needed attention and are ‘findable’ with a matching title.

Anyhow …

You can reuse recognizers. You have to recycle/destroy a recognizer once you receive a cancel-event with an error code (we plan to remove this issue in a future version of the SDK).

RecognizeOnce has a limit of 15 seconds, so the recognition will only produce one result, even for a longer stream.
For ContinuousRecognition, you will receive a Cancel event with the information ‘end of audio’ at the end of the audio stream.
If you using microphone input, you can call RecognizeOnce or Start/StopContinuousRecognition multiple times. It will take the current audio stream from the microphone.

Regarding EndSilenceTimeout: First of all, the service properties help to tweak the settings of the speech service. They are often used by us to test different scenarios, and we are trying to make the standard settings optimal for a wide range of scenarios (recognition rate, performance, etc). We hope that customers don’t need to tweak these parameters, also because the relationship between the parameters and the impact on the service behavior is often not easily explainable. 

I got some more information from the researchers and engineers about the EndSilenceTimeout property. There general statement was that it shouldn’t be set to a low value, since it will conflict with stream segmentation, and then create very unpredictable results. From my point of view (and checking the SDK code again) the EndSilenceTimeout implementation in the SDK is correct and behaving as expected, unfortunately not a trivial parameter 😉. I talked also to Chris about his comment to this issue, he is proposing a more customer friendly property in the SDK and the service. But this will not be available until late this year. 

What scenario did you try to resolve/improve with the EndSilenceTimeout property?

thx
Wolfgang

**Comment by robshostak** [comment]
Hi, Wolfgang –

 

Thanks so much for your detailed explanations.   Very helpful, as the API documentation doesn’t address all of these issues, and you’ve really clarified them for me.   In the future, I’ll be sure to post all such technical questions on the Forum so everyone can benefit.

 

To answer your question about my interest in the EndSilenceTimeoutMs property, the setting can be important for optimizing the response time to the user, especially if the recognition grammar consists only of short utterances such as “Scroll down”.  

 

I founded a Silicon Valley company called Vocera Communications (www.vocera.com <http://www.vocera.com>   NYSE:VCRA) about 20 years ago that makes speech-enabled  StarTrek-like communicator badges used by nurses and doctors in hospitals.   We found it of value to use the data we gathered from our users to adjust  recognition parameters including end silence but also confidence levels (we were using the Nuance speech recognition engine at the time).   This was long before Siri – at one point, Steve Jobs got interested in our system and installed it in several stores here in the San Francisco area.

 

Best –

Rob

**Comment by wolfma61** [comment]
Hi Bob - 

'recognizeOnce' is already tuned for command like scenarios with special settings to optimize the time until a phrase is recognized.  With property settings (detailed output, nbest results, confidence values) you can get probably a bunch of addition metadata you might find helpful (I think confidence is just being deployed ... I would have to double-check).

Our keyword spotter could help you train a keyword to get the recognition started. I would recommend a device with a good microphone (like in the Speech Device Kit or in Azure Kinect) to get the best recognition experience with keyword spotting.

Wolfgang

**Comment by chrisbasoglu** [comment]
Here is the actual definition of what EndSilenceTimeout does:  It will end the recognition from the time of the last result (intermediate, phrase or final) after the timeout expires.  Silence does not pay a part.  So our name here is very bad.  We will update the docs to say what this parameter actually does, and in the 1.8 release we will add the parameter that that controls the amount of silence used to judge when a phrase or final result is generated.  At that time we may also rename the EndSilenceTimeout parameter to a better name.

**Comment by LMIT-Dev** [comment]
Was this issue addressed in release 1.8 or not
The release notes do not mention anything, yet this ticket is closed

**Comment by robshostak** [comment]
Hi, Hendrik –

 

The person who responded to me closed the ticket soon after having replied that this property does not do what one would expect.   I don’t know whether it is fixed in 1.8.   Classically, EndSilenceTimeout is extremely useful for optimizing recognition speed – however, the person who had responded to my query thought that the speech engine does a reasonably good job of endpointing anyway.   Please let me know if you are able to get any more information.

 

Regards-

Rob Shostak

**Comment by LedanDark** [comment]
> Here is the actual definition of what EndSilenceTimeout does: It will end the recognition from the time of the last result (intermediate, phrase or final) after the timeout expires. Silence does not pay a part. So our name here is very bad. We will update the docs to say what this parameter actually does, and in the 1.8 release we will add the parameter that that controls the amount of silence used to judge when a phrase or final result is generated. At that time we may also rename the EndSilenceTimeout parameter to a better name.

https://github.com/chrisbasoglu

What is the name of the new parameter that controls when a phrase or final result is generated?

**Comment by rtrujillor** [comment]
I Imagine this improvement hasn't been added in the latest releases ( 1.11 right now and I can't see anything) . To have a  silence measurement until a speech is considered finished will be great and very valuable to let the users configure how the RecognizeOne feature works.
We have implemented a mobile application with commands support and sometimes two seconds is not enough, and the recognition ends just because the user has paused the speech a bit.
Thanks for the feedback.

**Comment by supercatcity** [comment]
> Here is the actual definition of what EndSilenceTimeout does: It will end the recognition from the time of the last result (intermediate, phrase or final) after the timeout expires. Silence does not pay a part. So our name here is very bad. We will update the docs to say what this parameter actually does, and in the 1.8 release we will add the parameter that that controls the amount of silence used to judge when a phrase or final result is generated. At that time we may also rename the EndSilenceTimeout parameter to a better name.

This bug is still exist. And I have not find a parameter which could controls the amount of silence used to judge when a phrase or final result is generated.

**Comment by rhurey** [comment]
There isn't an exposed parameter to control phrase segmentation times.

EndSilenceTimeout is the amount of silence after a phrase before the SpeechService will indicate it's receiving silence. At that point a bunch of things internal to the Speech SDK and Speech Service communication contract will happen, and an event will be raised by the Speech SDK to indicate that the Speech Service is receiving silence. 

It only matters in continuous recognitions.
