### ISSUE TITLE
ServiceTimeout, Due to service inactivity the client buffer size exceeded. Resetting the buffer.

### ISSUE THREAD

**Issue by johnpaulu** [Azure-Samples/cognitive-services-speech-sdk#490]
**Describe the bug**
Sometimes the speech to text recognition is terminated due to ServiceTimeout. This issue does not occur regularly only sometimes. This seems to be caused by "service inactivity the client buffer size exceeded. Resetting the buffer.". 

**To Reproduce**
I am using the continuousRecognitionWithFileAsync sample from https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java

**Expected behavior**
The sample is expected to covert the audio file to text.

**Version of the Cognitive Services Speech SDK**
version 1.5

**Platform, Operating System, and Programming Language**
Microsoft Server 2016
.NET 3.5

**Additional context**
ServiceTimeout, Due to service inactivity the client buffer size exceeded. Resetting the buffer. SessionId: ed80199616b94568a0ea19acc23b1c01

**Comment by jhakulin** [comment]
Thanks for feedback, I would like to know more to be able to help you / reproduce the issue efficiently.
@johnpaulu How easily you can reproduce the issue with continuousRecognitionWithFileAsync ? Anything specific in the wav files you use (long or short) which trigger the issue ?
Could you provide a log using the instructions below ?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by johnpaulu** [comment]
Thanks, I have enabled the logging, and once the issue happens again I will share the logs. 
So far I have not managed to reproduce the issue. But in one case it happened for a bad quality recording from a conference call, which had no audio i.e. no sound for around 30 minutes, approximately from 15 minutes to 45 minutes of 1 hour file. Probably the conference tool that was used to record the call could not record the call for some reason during that period and therefore there was no sound. When I played that recording I could hear speakers normally for other periods. The termination happened in 30 minutes after the recognition process started. Initially I though the issue was caused by no audio data in the recording. However next time, it happened for a relatively good recording where I could hear speakers well for the entire period, again approximately for 1 hour recording file. The termination occurred in 25 minutes once the recognition process stared. When I split the file into 2 parts and processed each of them separately, then the speech recognition library was able to process the parts without the servicetime out. Next time the servicetimeout issue occurred again for a good recording, approximately 1 hour file, where I could hear speakers well during the entire period.

**Comment by johnpaulu** [comment]
[stt_2020-01-22_537b753a-f6e6-4a86-8c88-2c15e99e817a.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4100259/stt_2020-01-22_537b753a-f6e6-4a86-8c88-2c15e99e817a.txt)
Please find the attached log

**Comment by rhurey** [comment]
Thanks. I looked through the first session you referenced and the log attached, they were very helpful.

I'm going to need to consult with some colleagues about this, but we have good information to go on for what's happening and I'll get back with more information.

In the mean time, have you considered using the REST API to transcribe longer wav files? There's a sample here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/from-blob?pivots=programming-language-java

**Comment by rhurey** [comment]
We've identified a service side change that should resolve this issue and are working on getting it rolled out.

**Comment by eldakms** [comment]
The change has been deployed to UKSouth, @johnpaulu could you please try and see whether you still see the issue? Thank you!

**Comment by johnpaulu** [comment]
Thanks, it's OK now, I will also observer the issue for a longer period of time

**Comment by eldakms** [comment]
Thank you!

**Comment by jschenxiaoyu** [comment]
I had the same problem. After I change the service region to UKSouth, this problem still remains sometimes when I test on a wav file longer than 1 hour.

**Comment by eldakms** [comment]
by chance, does your audio contain music/noise?

**Comment by jschenxiaoyu** [comment]
> by chance, does your audio contain music/noise?

In above log files, ab357e0f48ab4516bde6f43d9e1c2d58-1.wav and ab357e0f48ab4516bde6f43d9e1c2d58-2.wav contain background music. 
3bcc957d10c3436791b56f885e683e5c-2.wav contains some noise.

**Comment by eldakms** [comment]
Currently there is a known issue with music files, if you send them faster than 1x natural speech - you can get this timeout. We are working on a fix. Meanwhile you can send with the speed of  1x natural speech.

**Comment by jschenxiaoyu** [comment]
> Currently there is a known issue with music files, if you send them faster than 1x natural speech - you can get this timeout. We are working on a fix. Meanwhile you can send with the speed of 1x natural speech.

How can I send with the speed of 1x natural speech? I am using continuousRecognitionWithFileAsync sample. Thank you very much.

**Comment by pankopon** [comment]
Hi, based on discussion with rhurey there is currently no "easy" method to force 1x (real-time) transfer speed. One way would be to use a pull stream and implement PullAudioInputStreamCallback so that the average bytes per second for input is equal to a real-time transfer rate.

**Comment by pankopon** [comment]
@eldakms Any update on the fix for music files that you mentioned, has it been released?

**Comment by eldakms** [comment]
yes, the decoder was updated a month ago or so.

**Comment by johnpaulu** [comment]
Hi, 

the service timeout issue I have reported above on 21st January has not reoccurred since your fix was deployed on 30th January for UKSouth, however, yesterday I have experienced it again. Please find the attached collected debug logs (currently using speech-sdk 1.7, openjdk 1.8)

Thanks

[stt_2020-04-25_0439bfc5-d790-428f-92bf-5b8da473047b.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4533829/stt_2020-04-25_0439bfc5-d790-428f-92bf-5b8da473047b.txt)

**Comment by pankopon** [comment]
@johnpaulu Sorry for no update - is the timeout still reoccurring for you with the latest SDK and services?

**Comment by oscholz** [comment]
@johnpaulu I've added a bug to our backlog for this. We will review this as part of our next sprint(s). We will update you here once we resolve the associated bug.

**Comment by johnpaulu** [comment]
Hi, the issue started to appear again today. Was there any change in UKSouth?

**Comment by marlon-br** [comment]
I also met this issue today. It was OK earlier and now I constantly receive this error after 10 minutes of speech recognized. Looks like a critical degradation.

I see the issue on 1.13.0

**Comment by eldakms** [comment]
@marlon-br  what region? could you please share some session ids? thanks!

**Comment by marlon-br** [comment]
@eldakms region is "eastus" and i use paid subscription.
I have no idea how to get session id

**Comment by marlon-br** [comment]
@eldakms Here we go: SessionId:fa3e3c02857de0c48816debe94ce0785 ResultId:a121c870d0f1aa5499edb8cdfafe34ed CancellationReason:Error CancellationErrorCode:ServiceTimeout Error details:Due to service inactivity the client buffer size exceeded. Resetting the buffer. SessionId: fa3e3c02857de0c48816debe94ce0785

**Comment by eldakms** [comment]
Are you sending the audio from a file? I see 1.7x speed of natural speech on the server side.

**Comment by marlon-br** [comment]
@eldakms yes, it comes from file and earlier everything was fine

**Comment by eldakms** [comment]
The problem is that the service side only guarantees recognition with the speed on natural speech, for other scenarios there is batch API. Usually the service does ~2x depending on the content of the audio (i.e. if there is music it is usually slower). In your case i see 1.7x. Now, SDK pushes with 2x speed, if no connection is broken/no much silence in audio, my understanding is that SDK does not check the non-confirmed buffer. But as soon as there was a reconnect, SDK checks and if the buffer exceeds 30 seconds of audio - it gives the above error. I see many reconnects for your session id, i think this is exactly what is happening. Probably somebody from the SDK team can confirm.

**Comment by marlon-br** [comment]
@eldakms thank you for your investigations, but what is the solution?

I don't do anything special - android application, audio data and push stream to send data to the service. I do not manage connection, it is on sdk side and do not control buffer, its also on sdk or service side. Could you please advise how to fix the issue?

**Comment by liankuai** [comment]
Hi
I have the same issue on dev speech portal(https://develop.speech.microsoft.com/) today ,  I used the Editor-WestUS resource, and audio more than 1hour.

![1](https://user-images.githubusercontent.com/27266267/103622539-d6e28400-4f71-11eb-9a28-823989f3b7eb.png)
Number of success: 0
Number of failure: 1

1hour.wav	Speech service: SessionId=a07e263545dc46f88caf06df86de6a62, ErrorCode=ServiceTimeout, ErrorDetails=Due to service inactivity the client buffer size exceeded. Resetting the buffer. SessionId: a07e263545dc46f88caf06df86de6a62

**Comment by dargilco** [comment]
Thank you @liankuai from your comment. We understand the issue and discussing how to fix it in the Speech SDK. The recommended workaround is to use [batch transcription](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription), which was built for processing long audio files. Tagging @eldakms as well.

**Comment by marlon-br** [comment]
@liankuai hi, since there is no fix for a very long time, I use Speech SDK for short audios and Batch API for long audios :)

**Comment by liankuai** [comment]
> Thank you @liankuai from your comment. We understand the issue and discussing how to fix it in the Speech SDK. The recommended workaround is to use [batch transcription](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription), which was built for processing long audio files. Tagging @eldakms as well.

Thank you very much.

**Comment by liankuai** [comment]
> @liankuai hi, since there is no fix for a very long time, I use Speech SDK for short audios and Batch API for long audios :)

Thank you very much.

**Comment by dargilco** [comment]
A fix for this issue will be included in Speech SDK version 1.17 likely to be released around mid-May. The recommendation however remains the same: very long audio WAV files should be transcribed using [batch transcription](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription)

**Comment by marcelgerber** [comment]
I also was facing this issue and had a really hard time figuring it out.
I'm running the `spx` cli through docker, and was getting this error _almost every time_.

In the end, I realized that it was caused by slow upload speeds, stemming from other devices in my WiFi uploading big files at the same time as `spx` is running. Pausing these uploads did resolve the issue.

I hope this is helpful to someone else who is also facing this issue! :)

**Comment by bobir01** [comment]
I am facing this issue again even with short-sized wav files lengths of 2-3 minutes, I am using azure-cognitiveservices-speech==1.29.0 , python3.10, I am using recognize_once() function with file source audio file

**Comment by KyrieZhang11** [comment]
Hi I am facing this issue again when using ConversationTranscriber to startTranscribingAsync(), 
when there is no voice,  "Due to service inactivity, the client buffer exceeded maximum size. Resetting the buffer." always happened at 66s.
If we use SpeechRecognizer with the same configuration, we won't have this problem.
Here is our log.
The region is eastus

[speechLog.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12426294/speechLog.txt)
