### ISSUE TITLE
The speech-to-text result may be incomplete

### ISSUE THREAD

**Issue by zhengxiang0808** [Azure-Samples/cognitive-services-speech-sdk#500]
**Describe the bug**
When I do continuous speech recognition with input from an audio file, by referring to the "speech_recognize_continuous_from_file" method from "https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py", the result I get may be incomplete.

For example, given that, the speech contains 10 sentences, but the result may just contain 5 or 6 ones. In another word, after I get 5 or 6 sentences, I receive the stopped signal. Well, the actual number of the sentences is uncertain, maybe I could get all fortunately. However, the sentences I get is the front ones definitely.

**To Reproduce**
1. Prepare a speech file
2. Do continuous speech recognition by referring to the "speech_recognize_continuous_from_file" method  from "https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py" several times

**Expected behavior**
The result should contain all the sentences of the speech.
In the beginning, maybe the result is complete. But after several times, the result could just contain the front several sentences.

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech 1.9.0

**Platform, Operating System, and Programming Language**
 - OS: Mac OS
 - Hardware
 - Programming language:  Python
 - Browser: Chrome

**Comment by rhurey** [comment]
Well, sorry you're hitting this.

We do test with multiple phrases and continuous recognition and I haven't seen a limit get hit.

Can you share either a session ID for a recognition that ended early, or the audio file?

**Comment by zhengxiang0808** [comment]
Well, thanks for your attention~

These are the session ID:

6f933889f280408590671cbd8adec5a8
4f26e1ec479d46fd82e1557fe4455353
5c0fd5e3a8384323a3b5adee42ea7aff
b5605cdcac894769a2f54858d42a76dd

Looking forward for your reply~

**Comment by jaycollett** [comment]
I'm having a very similar issue with the quickstart code (basic) and a test wave file of random words being spoken. I always get 100% match but it always stops at ~30-35 seconds (audio time). I never get the full transcription.

**Comment by pankopon** [comment]
@zhengxiang0808 or @jaycollett - could either of you please attach an audio file that you can reproduce the issue with?

**Comment by satbecse** [comment]
We are trying to do continousSpeechRecognition with Azure Speech to Text SDK  from 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console. 

But it is never giving us the full transcript. But when we run in a debug mode it works. 

In normal spring boot application, when we pass .wav input ,it only outputs a partial transcript and it is not a complete one.

But, when we run in the debug mode in Eclipse , when we pass same .wav input ,it outputs full transcript and it is good.


 Can you please help us here ?

**Comment by pankopon** [comment]
If possible, please attach an input audio file, preferably with a full expected transcript, that you can reproduce the issue with.

**Comment by zhengxiang0808** [comment]
> If possible, please attach an input audio file, preferably with a full expected transcript, that you can reproduce the issue with.

The file I can upload must be smaller than 10MB...

But it doesn't matter which the audio is, any can be used to do the test. After you call the api for one wav file many times, the result will became abnormal. 

The key is "repeating for one file".

Interesting, when the problem happen, you feed a new file, the system can do well with the new one. It seems like the program may be tired of processing the same thing~

**Comment by oscholz** [comment]
Thank you for this bug report @zhengxiang0808, @jaycollett, @satbecse!
I've added this to our backlog. We will review this and if we can repro it, will address it in a future release. Once the work is done, we will update this issue to let you know what release the feature/fix will be in.
In the meantime, you can always try the latest release of the Speech SDK (v. 1.12.1) and see if this still repros. If you do please let us know what you find by commenting in this issue.
We also released a new tool called SPX that might help with this:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/spx-basics?tabs=windowsinstall
SPX is a command line tool you can use to send files to the Speech service. If you do try it, please let us know if the bug repros for you with SPX.

**Comment by ronlockard** [comment]
I just experienced this issue.  I am attaching a file that recreates this issue still with version 1.24.2 of the python sdk.
The full transcription should be "No one ever. No. Speak to service manager."  I get back "No one. Ever."
[fee08c3b0e2156755cd6dfa379c3d4f1_customer_intent.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/10141994/fee08c3b0e2156755cd6dfa379c3d4f1_customer_intent.zip)
